# fly.toml app configuration file
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "binance-monitor"
primary_region = "ams"  # Amsterdam - EU region to avoid Binance restrictions
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  builder = "dockerfile"

[env]
  PORT = "8080"
  PYTHONUNBUFFERED = "1"

[experimental]
  auto_rollback = true

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0

  [[services.http_checks]]
    interval = "10s"
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = "2s"
    tls_skip_verify = false
    [services.http_checks.headers]

# Machine resources
[vm]
  size = "shared-cpu-1x"
  memory = "256mb"

# Auto-scaling configuration
[[metrics]]
  port = 9091
  path = "/metrics"